In [1]:
from env.env import VexEnv
from config import VexConfig
import torch

In [2]:
config = VexConfig()
env = VexEnv(config)

In [3]:
env_out = env.reset()

In [4]:
torch.allclose(env_out['observations']['robot_red']['core_obs'], env_out['observations']['robot_blue']['core_obs'])

True

In [19]:
x_bin, y_bin, theta_bin = 10, 10, 10
move_id = 0
env_out = env.step({
    'robot_red': [move_id, x_bin, y_bin, theta_bin],
    'robot_blue': [move_id, x_bin, y_bin, theta_bin],
})

In [20]:
torch.allclose(env_out['observations']['robot_red']['core_obs'], env_out['observations']['robot_blue']['core_obs'])

True

In [7]:
env_out['observations']['robot_red']['core_obs']

tensor([ 0.0017,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,  1.0000,
         0.0000,  0.0000,  1.0000,  0.0000,  0.0000,  1.0000,  0.2136,  0.5000,
         0.3090, -0.9511,  0.7864,  0.5000, -0.3090,  0.9511,  0.0000,  0.0000,
         0.2000,  0.0536, -0.3331,  0.2386, -0.1539,  0.9881,  0.5191, -0.3331,
         0.4361,  0.6336,  0.7737,  0.0536,  0.3331,  0.2386,  0.4563, -0.8898,
         0.5191,  0.3331,  0.4361,  0.9673, -0.2535,  0.1877, -0.0986,  0.1500,
         0.6983,  0.7159,  0.3850,  0.0986,  0.2810,  0.9980,  0.0633,  0.1877,
         0.0986,  0.1500,  0.9857, -0.1687,  0.3850, -0.0986,  0.2810,  0.8446,
         0.5354, -0.1197, -0.3331,  0.2503, -0.6124,  0.7905, -0.1197,  0.3331,
         0.2503, -0.0308, -0.9995,  0.6924,  0.3331,  0.5433,  0.9910, -0.1338,
         0.6924, -0.3331,  0.5433,  0.7231,  0.6907])

In [8]:
env_out['observations']['robot_blue']['core_obs']

tensor([ 0.0017,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,  1.0000,
         0.0000,  0.0000,  1.0000,  0.0000,  0.0000,  1.0000,  0.2136,  0.5000,
         0.3090, -0.9511,  0.7864,  0.5000, -0.3090,  0.9511,  0.0000,  0.0000,
         0.2000,  0.0536, -0.3331,  0.2386, -0.1539,  0.9881,  0.5191, -0.3331,
         0.4361,  0.6336,  0.7737,  0.0536,  0.3331,  0.2386,  0.4563, -0.8898,
         0.5191,  0.3331,  0.4361,  0.9673, -0.2535,  0.1877, -0.0986,  0.1500,
         0.6983,  0.7159,  0.3850,  0.0986,  0.2810,  0.9980,  0.0633,  0.1877,
         0.0986,  0.1500,  0.9857, -0.1687,  0.3850, -0.0986,  0.2810,  0.8446,
         0.5354, -0.1197, -0.3331,  0.2503, -0.6124,  0.7905, -0.1197,  0.3331,
         0.2503, -0.0308, -0.9995,  0.6924,  0.3331,  0.5433,  0.9910, -0.1338,
         0.6924, -0.3331,  0.5433,  0.7231,  0.6907])

In [9]:
env_out['observations']['robot_red']['core_obs'] - env_out['observations']['robot_blue']['core_obs']

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
env_out['observations']['robot_red']['ball_obs'] - env_out['observations']['robot_blue']['ball_obs']

tensor([[ 0.6487, -0.9770,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.7080, -0.9770,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.6487,  0.9770,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.9633, -0.6662,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.9633, -0.6662,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.9633, -0.6662,  0.0000,  ...,  0.0000,  0.0000,  0.0000]])